TILE_SIDE_HEIGHT = 448
TILE_SIDE_WIDTH = 448

TILE_STRIDE_VERTICAL = TILE_SIDE_HEIGHT // 4
TILE_STRIDE_HORIZONTAL = TILE_SIDE_WIDTH // 4

DEFECT_CLASSIFICATION_CLASSES = [
    'corrosion',
    'peel',
]
