TILE_SIDE_HEIGHT = 224
TILE_SIDE_WIDTH = 224

TILE_STRIDE_VERTICAL = TILE_SIDE_HEIGHT // 4
TILE_STRIDE_HORIZONTAL = TILE_SIDE_WIDTH // 4

DEFECT_CLASSIFICATION_CLASSES = [
    'corrosion',
    'peel',
]

PREDICTION_THRESHOLD = 0.8
CLASSIFICATION_MODEL_NAME = 'vgg19'